#!/bin/bash
if ! . gif-anim-settings; then
	echo 'Error importing gif-anim-settings' >&2
	exit 1
fi

mkdir -p "$ga_dir_base"
mkdir -p "$ga_dir_frames"
rm "$ga_dir_frames"/*."$ga_frame_ext"

printf '%s' "$ga_hotkey_comments"
co=$(slop)
# co=285x184+289+669   # Test
echo "Coordinates chosen: $co"
echo "$co" > "$ga_fn_coords"
echo "Coordinates written to: $ga_fn_coords"
echo "Frames folder cleared: $ga_dir_frames/*"
echo "Ready for gif-anim-cap-frame"
