#!/bin/bash
which gif-anim-settings >/dev/null || {
	echo 'gif-anim-settings needs to be in your path (or modify the scripts to point directly to it)' >&2;
	exit 1;
}
. gif-anim-settings || {
	echo 'Error running gif-anim-settings to get settings' >&2;
	exit 1;
}

mkdir -p "$ga_dir_base"
mkdir -p "$ga_dir_frames"

# Attempt to ensure some security by changing to the frames cache dir
# and removing the files with the image extension from there.
# ...instead of the earlier version that did:
#      rm "$ga_dir_frames"/*."$ga_frame_ext"
# We do it in a subshell so we don't change directories here,
# not that # it matters much, since nothing else is done
# that's dependent on the current dir.
echo
echo "Wiping prior session frames: $ga_dir_frames/*.$ga_frame_ext"
(cd "$ga_dir_frames" && rm *."$ga_frame_ext" 2>/dev/null)

printf '%s' "$ga_hotkey_comments"
co=$(slop)
# co=285x184+289+669   # Test
echo "Coordinates chosen: $co"
echo "$co" > "$ga_fn_coords"
echo "Coordinates written to: $ga_fn_coords"
echo "Frames folder cleared: $ga_dir_frames/*"
echo "Ready for gif-anim-cap-frame"
